const baseExternal = [
  'path',
  'react',
  'react-dom',
  'react/jsx-runtime',
  'jsx-runtime',
  'react-jsx',
  'postcss',
  'autoprefixer',
  'react',
  'react-dom',
  'tailwindcss',
  'tw-animate-css',
  'tailwind-merge',
  'lucide-react',
  '@tailwindcss/vite',
  'clsx',
  'class-variance-authority',
]

const radixPackExternal = [
  "@radix-ui/react-accordion",
  "@radix-ui/react-alert-dialog",
  "@radix-ui/react-aspect-ratio",
  "@radix-ui/react-avatar",
  "@radix-ui/react-checkbox",
  "@radix-ui/react-collapsible",
  "@radix-ui/react-dialog",
  "@radix-ui/react-dropdown-menu",
  "@radix-ui/react-hover-card",
  "@radix-ui/react-label",
  "@radix-ui/react-menubar",
  "@radix-ui/react-navigation-menu",
  "@radix-ui/react-popover",
  "@radix-ui/react-progress",
  "@radix-ui/react-radio-group",
  "@radix-ui/react-scroll-area",
  "@radix-ui/react-select",
  "@radix-ui/react-separator",
  "@radix-ui/react-slider",
  "@radix-ui/react-slot",
  "@radix-ui/react-switch",
  "@radix-ui/react-tabs",
  "@radix-ui/react-toast",
  "@radix-ui/react-toggle",
  "@radix-ui/react-toggle-group",
  "@radix-ui/react-tooltip",
]


const packExternal = [
  'lucide-react',
  'class-variance-authority',
  '@hookform/resolvers',
  'cmdk',
  'date-fns',
  /date-fns\/.*/,
  'embla-carousel-react',
  'input-otp',
  'next-themes',
  'react-day-picker',
  'react-hook-form',
  'react-resizable-panels',
  'recharts',
  'sonner',
  'vaul',
  '@tanstack/react-table',
  '@tanstack/table-core',
  'react-dropzone',
  'react-textarea-autosize',
]

export const external = [
  ...baseExternal,
  ...radixPackExternal,
  ...packExternal,
]
